### ISSUE TITLE
No metrics created in prometheus

### ISSUE THREAD

**Issue by cedvan** [rverchere/ovh-mks-exporter#14]
Hi,

Thank you to this project 😃 !

I have created an dedicated OVH key unlimited with `GET *`
*(Permissions is correct and suffisant ? Not indicated in README 😉 )

Try use it with kube-prometheus-stack.
Deploy chart kube-prometheus-stack and mks YAML with Kustomize and ArgoCD.

Pod, service and servicemonitor are OK.

pod logs : 
```
time="2024-01-29T13:31:27Z" level=info msg="Starting application..."
time="2024-01-29T13:31:27Z" level=info msg="Starting exporter, enjoy!"
```

But metrics not created in my prometheus, so Grafana dashboard stay empty.
*Used dashboard : https://grafana.com/grafana/dashboards/19440-ovh-mks-metrics (this information is missing in README 😉 )*

`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 55.7.1
    namespace: service-monitoring
    releaseName: monitoring
    valuesFile: config/kube-prometheus-stack.values.yaml
    includeCRDs: true

resources:
  - https://raw.githubusercontent.com/rverchere/ovh-mks-exporter/main/deployment/deployment.yaml
  - https://raw.githubusercontent.com/rverchere/ovh-mks-exporter/main/deployment/service.yaml
  - https://raw.githubusercontent.com/rverchere/ovh-mks-exporter/main/deployment/servicemonitor.yaml
  - secrets/sealed-secret-ovh-mks-exporter.yaml

patches:
  - path: patches/ingress-alertmanager.yaml
  - path: patches/ingress-grafana.yaml
  - path: patches/ingress-prometheus.yaml
  - path: patches/ovh-mks-exporter/servicemonitor.yaml
```

`patches/ovh-mks-exporter/servicemonitor.yaml`
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-ovh-mks-exporter
  labels:
    release: monitoring
```

Maybe prom release label is bad in service monitor ?

**Comment by rverchere** [comment]
Hi!

Are you able to get raw metrics from the exporter, using kubectl port-forward and curl?

On the serviceMonitor, there are 2 things that are specific :
- namespaceSelector, which is "observality" for me https://github.com/rverchere/ovh-mks-exporter/blob/main/deployment/servicemonitor.yaml#L17
- release name, which is "prom" for me, and you have to change to your prometheus releasename (you already did it)

Thanks for reporting this ;)

**Comment by cedvan** [comment]
Thank you for responding :)

_Are you able to get raw metrics from the exporter, using kubectl port-forward and curl?_

With port-forward on service, curl on route `/metrics` respond : 

```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 9
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.19.12"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 178752
....
```

_namespaceSelector, which is "observality" for me https://github.com/rverchere/ovh-mks-exporter/blob/main/deployment/servicemonitor.yaml#L17_

My kube prometheus stack is installed in namespace `service-monitoring`

So I have updated my service monitor patch :

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-ovh-mks-exporter
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - service-monitoring
```

But always no ovh metrics presents in my prometheus.

Namespace selector need namespace where prometheus is installed, you confirm ?
